mongodb-labs/ai-ml-pipeline-testing

.evergreen/config.yml
The intended usage in to use [`Periodic Builds`](https://docs.devprod.prod.corp.mongodb.com/evergreen/Project-Configuration/Project-and-Distro-Settings#periodic-builds) to run this `.yml` periodically rather than `cron`.
* https://spruce.mongodb.com/version/657b330ed1fe0704a07412c0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> PYTHON-4078: Remove `cron: @weekly` from .evergreen

.evergreen/provision-atlas.sh
Upgrading the local atlas installed to 1.16. This should enable support for `vectorSearch` index types.
=> chore: upgrade atlas to 1.16

.gitignore
I've added a pretty-standard python/mongodb `.gitignore` file. I will now remove any files mistakenly added in my other pull-request.
=> [PYTHON-4306] Added .gitignore

.evergreen/config.yml, README.md
See details in JIRA [PYTHON-4289].
In addition to describing the how and why of using git patch files, I've describe the approach of setting `$CLONE_URL` to point to a feature branch, likely on a fork, until the upstream maintainer merges any pull-requests.
=> [PYTHON-4289] Add documentation of new patching functionality

.evergreen/config.yml
We are seeing intermittent failures in a number of the integrations.
chatgpt-retrieval-plugin returns less results than requested. We address this by  waiting until we get the full response.
llama-index returns a different answer (after response synthesizer called by llama index). We address this by accepting either of the two reponses that we've seen.
=> [PYTHON-4307] Simple fixes for intermittent failures

semantic-kernel-python/run.sh
Add `.env` file containing `MONGODB_ATLAS_CONNECTION_STRING`.
Cleanup of how poetry environment is built and run. Standardizing.
=> [PYTHON-4037] Failures on semantic-kernel-python do to missing .env file.

.evergreen/config.yml
Merged test fix into chatgpt-retrieval-plugin's feature/mongodb-datastore branch. 
With that done, this commit poinyts evergreen back to that branch (until upstream maintainers merge.)
=> [PYTHON-4307] Merged fix in chatgpt-retrieval

.evergreen/provision-atlas.sh
Update atlas to 1.18. This is a precursor to supporting the `vectorSearch` type in atlas creation.
=> PYTHON-4287: Update Atlas CLI to 1.18

.evergreen/provision-atlas.sh
Found in **provision-atlas.sh** -- The `for file in $TARGET_DIR/indexes/*.json` loop now removes the quotes as it will expand the glob as one expression "$TARGET_DIR/indexes/*.json" --> "$TARGET_DIR/indexes/x.json, $TARGET_DIR/indexes/y.json" rather than do individual loop iterations. 
```bash
for file in "$TARGET_DIR/indexes/*.json"; do
echo $file "DELIMIT"
done
``` 
outputs, 
```bash
>> echo $TARGET_DIR/indexes/x.json $TARGET_DIR/indexes/y.json DELIMIT
```
```bash
for file in $TARGET_DIR/indexes/*.json; do
echo $file "DELIMIT"
done
``` 
outputs, 
```bash
>> echo $TARGET_DIR/indexes/x.json DELIMIT
>> echo $TARGET_DIR/indexes/y.json DELIMIT
```
Check #7 as it implements the correction. Documenting in its own PR for posterity.
=> [Bugfix]: Correct index population on provision-atlas.sh

.evergreen/config.yml
Now that we have an accepted pull-request onto the upstream main branch, we can update to our tests to run against this branch.
=> [PYTHON-4381] Change docarray branch from caseyclements to docarray/main

llama_index/patches/example_data.patch
Add patch file to llama_index as maintainer, hopefully temporarily, replaced with trivial example.
See discussion in pull-request: https://github.com/run-llama/llama_index/pull/12854
Maintainer did not want a dependency on a text file that was already in the repo! "pants is annoying as hell to configure to rely on external files like text files."
I will work with him to get a non-trivial test but in the meantime, this will run against inputs that have more than one "node".
=> Add patch file to llama_index

.github/workflows/lint.yml, .pre-commit-config.yaml
[It works!](https://github.com/Jibola/ai-ml-pipeline-testing/pull/2)
Will have a follow-up PR to fix all the new-found linting issues.
=> PYTHON-4687: Adding precommit and linting to repo

semantic-kernel-python/run.sh
Semantic kernel tests were failing due to the repo changing the location of its test suite. This PR provides the new test suite path.
=> [Task] Change semantic-kernel import path

.evergreen/config.yml, chatgpt-retrieval-plugin/run.sh, llama-index-python-kvstore/run.sh, llama-index-python-vectorstore/run.sh
I also used by branch from [INTPYTHON-414](https://jira.mongodb.org/browse/INTPYTHON-414) to fix the error in langchain.
=> INTPYTHON-413 Use venvs instead of base python

.evergreen/config.yml, .evergreen/setup-remote.sh, langgraph-python/run.sh
Depends on https://github.com/langchain-ai/langchain-mongodb/pull/29
=> INTPYTHON-427 Add langgraph to ai-ml-testing pipeline

langchain-python/run.sh, langgraph-python/run.sh
=> Update langchain and langgraph runners

langchaingo-golang/config.env
GODRIVER-3464
Now that https://github.com/tmc/langchaingo/pull/1025 is merged we can update the clone URL for langchain-go.
=> GODRIVER-3464 Update clone URL

.evergreen/config.yml, .evergreen/fetch-secrets.sh, .evergreen/utils.sh, langchain-python/config.env
Passing build: https://spruce.mongodb.com/version/67f3e82905cbfd000738a23b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> INTPYTHON-573 Use drivers-tools to run the local atlas server

.evergreen/config.yml, .evergreen/fetch-repo.sh, .evergreen/provision-atlas.sh, .evergreen/setup-remote.sh, .gitignore, pymongo-voyageai/config.env, pymongo-voyageai/run.sh
Passing build: https://spruce.mongodb.com/version/681185aff7c84b0007136c28/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> INTPYTHON-591 Add pymongo-voyageai to pipeline

.evergreen/config.yml, .evergreen/execute-tests.sh, .evergreen/fetch-repo.sh, .evergreen/teardown.sh, README.md, chatgpt-retrieval-plugin/config.env, docarray/config.env, haystack-embeddings/config.env, haystack-fulltext/config.env, langchain-python/config.env, langchaingo-golang/config.env, langgraph-python/config.env, llama-index-python-vectorstore/config.env, pymongo-voyageai/config.env, semantic-kernel-csharp/config.env, semantic-kernel-python/config.env
Patch build: https://spruce.mongodb.com/version/682207ba29bc5200076d2ad0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Run with: `--param REPO_ORG=blink1073 --param REPO_BRANCH=test-branch`
Relevant logs:
```
[2025/05/12 09:39:09.732] Running command 'subprocess.exec' in function 'fetch repo' (step 1 of 3).
[2025/05/12 09:39:10.030] Cloning repo -b test-branch https://github.com/blink1073/langchain-mongodb...
[2025/05/12 09:39:10.030] Cloning repo -b test-branch https://github.com/blink1073/langchain-mongodb... done.
[2025/05/12 09:39:10.030] Cloning into 'langchain-mongodb'...
[2025/05/12 09:39:10.030] Finished command 'subprocess.exec' in function 'fetch repo' (step 1 of 3) in 298.018571ms.
```
```
[2025/05/12 09:49:24.249] Running command 'subprocess.exec' (step 2 of 2) in block …
```
=> INTPYTHON-611 Make it easier to run patch builds

.evergreen/config.yml, .evergreen/setup-remote.sh, README.md, langchain-js/config.env, langchain-js/indexes/langchain_test.json, langchain-js/run.sh
This PR adds testing of langchainjs' mongodb integration in the testing pipeline.  This PR currently uses a branch from my fork of langchainjs.  If this PR is ready to merge before https://github.com/langchain-ai/langchainjs/pull/8154, I'll file a ticket to remove the reference to my langchainjs fork after https://github.com/langchain-ai/langchainjs/pull/8154 merges and we can merge this PR.
=> NODE-6950: add langchainjs to testing pipeline

langchaingo-golang/run.sh
There appears to be a regression in the expected error for non-tokenized filter and the test should now expect the following error:
> 'pageContent' needs to be indexed as filter
Suggest skipping the failing test for now, deferring the LCG update to GODRIVER-3606.
=> INTPYTHON-663 Skip non-tokenized filter test in langchaingo

crewai-tools/config.env, crewai-tools/test_mongodb_vector_search_tool.py
Depends on https://github.com/crewAIInc/crewAI-tools/pull/389, which fixes two errors upstream (now merged).
Additionally, we use a more powerful model and set its seed to get more stability.  Finally, I turned on debug logging which had helped me diagnose the errors.
I ran the local and remote tests 3 times to verify stability.
Passing build: https://spruce.mongodb.com/version/68813ec70bd5000007f4efda/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> INTPYTHON-686 Make crewai tests more reliable

semantic-kernel-csharp/run.sh
- Added the .NET 9 SDK to fix the build issues.
- Temporarily disabled most of the tests while we diagnose flakiness.
=> CSHARP-5686: Fix .NET build issues and disable most SK.NET tests

.evergreen/config.yml, README.md
Patch build: https://spruce.mongodb.com/task/ai_ml_pipeline_testing_test_crewai_tools_python_rhel_test_crewai_tools_remote_patch_d0e1c48628390d90fcefb0e04d272978026b86b5_68e4feae6923670007de1b84_25_10_07_11_51_33/logs?execution=3
I ran all of the remote Python tests 4 times and the error did not recur.
=> INTPYTHON-781 Switch to RHEL 8.9
